# Generated by Django 3.0.5 on 2021-01-11 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0)),
                ('balanceBTC', models.FloatField(default=0)),
                ('buyOrders', models.Field()),
                ('sellOrders', models.Field()),
                ('profit', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('position', models.Field(default='')),
                ('price', models.FloatField(default=0)),
                ('BTCs', models.FloatField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.Field(default='')),
                ('value', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
